"""add pending states table

Revision ID: 885c1578b699
Revises: 1d056c4b1f42
Create Date: 2026-04-28 12:41:38.632873

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '885c1578b699'
down_revision: Union[str, Sequence[str], None] = '1d056c4b1f42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
